---

###################################################
######## IOS Password change#######################
###################################################

- name: User Password change
  hosts: routers      ### inventory group from ./hosts.ini
  gather_facts: no

  vars_prompt:

    - name: password
      prompt: What is your password for user ciscoworks ios?

  tasks:

    - name: Change password user ciscoworks on routers
      cisco.ios.ios_user:
        name: ciscoworks
        configured_password: '{{ password }}'
        update_password: always
        state: present   
      register: result    

    - name: Display results
      debug:
        msg: "{{ result }}"

    - name: IOS >> Save Configuration to NVRAM
      ios_config:
        save_when: always
      register: output

    - name: DEBUG >> output
      debug:
        msg: "password was {{ password }}, {{ output }}"




###################################################
######## ASA Password change#######################
###################################################


- name: User Password ASA change
  hosts: firewalls   ### inventory group from ./hosts.ini
  gather_facts: no

  vars_prompt:

    - name: password
      prompt: What is your password for user ciscoworks asa?

  tasks:


    - name: Asa ciscowork password change
      cisco.asa.asa_config:
       lines:
        - username ciscoworks password {{ password }}
      register: output

    - name: save running to startup when modified
      #cisco.asa.asa_config:
      asa_config:
        save: yes
        #save_when: modified 


####################### Provide results of command #########################

    - name: DEBUG >> output
      debug:
       msg: "{{ output }}"   





    
  ############################################
  ############Switches nxos###################
  ############################################

- name: User Password change
  hosts: switches      ### inventory group from ./hosts.ini
  gather_facts: no

  vars_prompt:

    - name: password
      prompt: What is your password for user ciscoworks nxos?

  tasks:

    - name: Change password user ciscoworks on switches NXOS
      cisco.nxos.nxos_user:
        name: ciscoworks
        configured_password: '{{ password }}'
        update_password: always
        state: present   
      register: result    

    - name: Display results
      debug:
        msg: "{{ result }}"

    - name: NXOS >> Save Configuration to NVRAM
      nxos_config:
        save_when: always
      register: output

    - name: DEBUG >> output
      debug:
        msg: "password was {{ password }}, {{ output }}"


